[package]
name = "ps-str"
version = "0.1.0-1"
description = "String transcoding library"
license = "GPL-3.0-or-later"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
